name: CI - Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
# Note: add -2 mins for actual exexution time
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # schedule:
    # - cron: '58 4 * * 5' # runing time take 30 mins for 500 retries
    # - cron: '30 5 * * 5'
    # - cron: '35 5 * * 5'
    # - cron: '40 5 * * 5'
    # - cron: '45 5 * * 5'
    # - cron: '50 5 * * 5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.15.0-chrome96-ff94
    strategy:
      fail-fast: false
      matrix:
        spec: ['appoitment-booking']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          email: ${{ secrets.email }}
          # DEBUG: 'cypress:*'
        with:
          spec: cypress/integration/${{ matrix.spec }}.spec.js
          config: baseUrl=${{ secrets.baseUrl }}
          browser: chrome
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-${{ matrix.spec }}
          retention-days: 1
          path: |
            cypress/screenshots/
            cypress/videos/
